"""empty message

Revision ID: bc80ecd1d47e
Revises: 554f9507ec4d
Create Date: 2025-08-29 22:05:30.924237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc80ecd1d47e'
down_revision = '554f9507ec4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_dealer_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint('message_dealer_id_key', ['dealer_id'])

    # ### end Alembic commands ###
